/*
Gerrit Checks Plugin REST API

REST endpoints contributed by the checks plugin. Paths, parameters and payload schemas are generated statically from the plugin's REST bindings; human-authored summaries, descriptions and examples are mined from the plugin's rest-api*.md and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package checksclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// CheckersAPIService CheckersAPI service
type CheckersAPIService service

type ApiGetPluginsChecksCheckersRequest struct {
	ctx context.Context
	ApiService *CheckersAPIService
}

func (r ApiGetPluginsChecksCheckersRequest) Execute() ([]CheckerInfo, *http.Response, error) {
	return r.ApiService.GetPluginsChecksCheckersExecute(r)
}

/*
GetPluginsChecksCheckers List Checkers

Retrieves all checkers.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetPluginsChecksCheckersRequest
*/
func (a *CheckersAPIService) GetPluginsChecksCheckers(ctx context.Context) ApiGetPluginsChecksCheckersRequest {
	return ApiGetPluginsChecksCheckersRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []CheckerInfo
func (a *CheckersAPIService) GetPluginsChecksCheckersExecute(r ApiGetPluginsChecksCheckersRequest) ([]CheckerInfo, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []CheckerInfo
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CheckersAPIService.GetPluginsChecksCheckers")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/plugins/checks/checkers"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetPluginsChecksCheckersCheckerIdRequest struct {
	ctx context.Context
	ApiService *CheckersAPIService
	checkerId string
}

func (r ApiGetPluginsChecksCheckersCheckerIdRequest) Execute() (*CheckerInfo, *http.Response, error) {
	return r.ApiService.GetPluginsChecksCheckersCheckerIdExecute(r)
}

/*
GetPluginsChecksCheckersCheckerId Get Checker

Retrieves a checker.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param checkerId
 @return ApiGetPluginsChecksCheckersCheckerIdRequest
*/
func (a *CheckersAPIService) GetPluginsChecksCheckersCheckerId(ctx context.Context, checkerId string) ApiGetPluginsChecksCheckersCheckerIdRequest {
	return ApiGetPluginsChecksCheckersCheckerIdRequest{
		ApiService: a,
		ctx: ctx,
		checkerId: checkerId,
	}
}

// Execute executes the request
//  @return CheckerInfo
func (a *CheckersAPIService) GetPluginsChecksCheckersCheckerIdExecute(r ApiGetPluginsChecksCheckersCheckerIdRequest) (*CheckerInfo, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CheckerInfo
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CheckersAPIService.GetPluginsChecksCheckersCheckerId")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/plugins/checks/checkers/{checker-id}"
	localVarPath = strings.Replace(localVarPath, "{"+"checker-id"+"}", url.PathEscape(parameterValueToString(r.checkerId, "checkerId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPostPluginsChecksCheckersRequest struct {
	ctx context.Context
	ApiService *CheckersAPIService
	checkerInput *CheckerInput
}

func (r ApiPostPluginsChecksCheckersRequest) CheckerInput(checkerInput CheckerInput) ApiPostPluginsChecksCheckersRequest {
	r.checkerInput = &checkerInput
	return r
}

func (r ApiPostPluginsChecksCheckersRequest) Execute() (*CheckerInfo, *http.Response, error) {
	return r.ApiService.PostPluginsChecksCheckersExecute(r)
}

/*
PostPluginsChecksCheckers Create Checker

Creates a new checker.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiPostPluginsChecksCheckersRequest
*/
func (a *CheckersAPIService) PostPluginsChecksCheckers(ctx context.Context) ApiPostPluginsChecksCheckersRequest {
	return ApiPostPluginsChecksCheckersRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return CheckerInfo
func (a *CheckersAPIService) PostPluginsChecksCheckersExecute(r ApiPostPluginsChecksCheckersRequest) (*CheckerInfo, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CheckerInfo
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CheckersAPIService.PostPluginsChecksCheckers")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/plugins/checks/checkers"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "application/x-www-form-urlencoded"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.checkerInput
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPostPluginsChecksCheckersCheckerIdRequest struct {
	ctx context.Context
	ApiService *CheckersAPIService
	checkerId string
	checkerInput *CheckerInput
}

func (r ApiPostPluginsChecksCheckersCheckerIdRequest) CheckerInput(checkerInput CheckerInput) ApiPostPluginsChecksCheckersCheckerIdRequest {
	r.checkerInput = &checkerInput
	return r
}

func (r ApiPostPluginsChecksCheckersCheckerIdRequest) Execute() (*CheckerInfo, *http.Response, error) {
	return r.ApiService.PostPluginsChecksCheckersCheckerIdExecute(r)
}

/*
PostPluginsChecksCheckersCheckerId Update Checker

Updates a checker.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param checkerId
 @return ApiPostPluginsChecksCheckersCheckerIdRequest
*/
func (a *CheckersAPIService) PostPluginsChecksCheckersCheckerId(ctx context.Context, checkerId string) ApiPostPluginsChecksCheckersCheckerIdRequest {
	return ApiPostPluginsChecksCheckersCheckerIdRequest{
		ApiService: a,
		ctx: ctx,
		checkerId: checkerId,
	}
}

// Execute executes the request
//  @return CheckerInfo
func (a *CheckersAPIService) PostPluginsChecksCheckersCheckerIdExecute(r ApiPostPluginsChecksCheckersCheckerIdRequest) (*CheckerInfo, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CheckerInfo
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CheckersAPIService.PostPluginsChecksCheckersCheckerId")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/plugins/checks/checkers/{checker-id}"
	localVarPath = strings.Replace(localVarPath, "{"+"checker-id"+"}", url.PathEscape(parameterValueToString(r.checkerId, "checkerId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "application/x-www-form-urlencoded"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.checkerInput
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
