/*
Gerrit Checks Plugin REST API

REST endpoints contributed by the checks plugin. Paths, parameters and payload schemas are generated statically from the plugin's REST bindings; human-authored summaries, descriptions and examples are mined from the plugin's rest-api*.md and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package checksclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
	"reflect"
)


// ChangesAPIService ChangesAPI service
type ChangesAPIService service

type ApiGetChangesChangeIdRevisionsRevisionIdChecksRequest struct {
	ctx context.Context
	ApiService *ChangesAPIService
	changeId string
	revisionId string
}

func (r ApiGetChangesChangeIdRevisionsRevisionIdChecksRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.GetChangesChangeIdRevisionsRevisionIdChecksExecute(r)
}

/*
GetChangesChangeIdRevisionsRevisionIdChecks List Checks

Retrieves all checks for a given revision and change.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param changeId
 @param revisionId
 @return ApiGetChangesChangeIdRevisionsRevisionIdChecksRequest
*/
func (a *ChangesAPIService) GetChangesChangeIdRevisionsRevisionIdChecks(ctx context.Context, changeId string, revisionId string) ApiGetChangesChangeIdRevisionsRevisionIdChecksRequest {
	return ApiGetChangesChangeIdRevisionsRevisionIdChecksRequest{
		ApiService: a,
		ctx: ctx,
		changeId: changeId,
		revisionId: revisionId,
	}
}

// Execute executes the request
//  @return interface{}
func (a *ChangesAPIService) GetChangesChangeIdRevisionsRevisionIdChecksExecute(r ApiGetChangesChangeIdRevisionsRevisionIdChecksRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ChangesAPIService.GetChangesChangeIdRevisionsRevisionIdChecks")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/changes/{change-id}/revisions/{revision-id}/checks"
	localVarPath = strings.Replace(localVarPath, "{"+"change-id"+"}", url.PathEscape(parameterValueToString(r.changeId, "changeId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"revision-id"+"}", url.PathEscape(parameterValueToString(r.revisionId, "revisionId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v interface{}
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetChangesChangeIdRevisionsRevisionIdChecksCheckIdRequest struct {
	ctx context.Context
	ApiService *ChangesAPIService
	changeId string
	revisionId string
	checkId string
	o *string
	o2 *[]string
}

func (r ApiGetChangesChangeIdRevisionsRevisionIdChecksCheckIdRequest) O(o string) ApiGetChangesChangeIdRevisionsRevisionIdChecksCheckIdRequest {
	r.o = &o
	return r
}

func (r ApiGetChangesChangeIdRevisionsRevisionIdChecksCheckIdRequest) O2(o2 []string) ApiGetChangesChangeIdRevisionsRevisionIdChecksCheckIdRequest {
	r.o2 = &o2
	return r
}

func (r ApiGetChangesChangeIdRevisionsRevisionIdChecksCheckIdRequest) Execute() (*CheckInfo, *http.Response, error) {
	return r.ApiService.GetChangesChangeIdRevisionsRevisionIdChecksCheckIdExecute(r)
}

/*
GetChangesChangeIdRevisionsRevisionIdChecksCheckId Get Check

Retrieves a check.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param changeId
 @param revisionId
 @param checkId
 @return ApiGetChangesChangeIdRevisionsRevisionIdChecksCheckIdRequest
*/
func (a *ChangesAPIService) GetChangesChangeIdRevisionsRevisionIdChecksCheckId(ctx context.Context, changeId string, revisionId string, checkId string) ApiGetChangesChangeIdRevisionsRevisionIdChecksCheckIdRequest {
	return ApiGetChangesChangeIdRevisionsRevisionIdChecksCheckIdRequest{
		ApiService: a,
		ctx: ctx,
		changeId: changeId,
		revisionId: revisionId,
		checkId: checkId,
	}
}

// Execute executes the request
//  @return CheckInfo
func (a *ChangesAPIService) GetChangesChangeIdRevisionsRevisionIdChecksCheckIdExecute(r ApiGetChangesChangeIdRevisionsRevisionIdChecksCheckIdRequest) (*CheckInfo, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CheckInfo
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ChangesAPIService.GetChangesChangeIdRevisionsRevisionIdChecksCheckId")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/changes/{change-id}/revisions/{revision-id}/checks/{check-id}"
	localVarPath = strings.Replace(localVarPath, "{"+"change-id"+"}", url.PathEscape(parameterValueToString(r.changeId, "changeId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"revision-id"+"}", url.PathEscape(parameterValueToString(r.revisionId, "revisionId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"check-id"+"}", url.PathEscape(parameterValueToString(r.checkId, "checkId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.o != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "O", r.o, "form", "")
	}
	if r.o2 != nil {
		t := *r.o2
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				parameterAddToHeaderOrQuery(localVarQueryParams, "o", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "o", t, "form", "multi")
		}
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPostChangesChangeIdRevisionsRevisionIdChecksRequest struct {
	ctx context.Context
	ApiService *ChangesAPIService
	changeId string
	revisionId string
	checkInput *CheckInput
}

func (r ApiPostChangesChangeIdRevisionsRevisionIdChecksRequest) CheckInput(checkInput CheckInput) ApiPostChangesChangeIdRevisionsRevisionIdChecksRequest {
	r.checkInput = &checkInput
	return r
}

func (r ApiPostChangesChangeIdRevisionsRevisionIdChecksRequest) Execute() (*CheckInfo, *http.Response, error) {
	return r.ApiService.PostChangesChangeIdRevisionsRevisionIdChecksExecute(r)
}

/*
PostChangesChangeIdRevisionsRevisionIdChecks Create Check

Creates a new check.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param changeId
 @param revisionId
 @return ApiPostChangesChangeIdRevisionsRevisionIdChecksRequest
*/
func (a *ChangesAPIService) PostChangesChangeIdRevisionsRevisionIdChecks(ctx context.Context, changeId string, revisionId string) ApiPostChangesChangeIdRevisionsRevisionIdChecksRequest {
	return ApiPostChangesChangeIdRevisionsRevisionIdChecksRequest{
		ApiService: a,
		ctx: ctx,
		changeId: changeId,
		revisionId: revisionId,
	}
}

// Execute executes the request
//  @return CheckInfo
func (a *ChangesAPIService) PostChangesChangeIdRevisionsRevisionIdChecksExecute(r ApiPostChangesChangeIdRevisionsRevisionIdChecksRequest) (*CheckInfo, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CheckInfo
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ChangesAPIService.PostChangesChangeIdRevisionsRevisionIdChecks")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/changes/{change-id}/revisions/{revision-id}/checks"
	localVarPath = strings.Replace(localVarPath, "{"+"change-id"+"}", url.PathEscape(parameterValueToString(r.changeId, "changeId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"revision-id"+"}", url.PathEscape(parameterValueToString(r.revisionId, "revisionId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "application/x-www-form-urlencoded"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.checkInput
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPostChangesChangeIdRevisionsRevisionIdChecksCheckIdRequest struct {
	ctx context.Context
	ApiService *ChangesAPIService
	changeId string
	revisionId string
	checkId string
	checkInput *CheckInput
}

func (r ApiPostChangesChangeIdRevisionsRevisionIdChecksCheckIdRequest) CheckInput(checkInput CheckInput) ApiPostChangesChangeIdRevisionsRevisionIdChecksCheckIdRequest {
	r.checkInput = &checkInput
	return r
}

func (r ApiPostChangesChangeIdRevisionsRevisionIdChecksCheckIdRequest) Execute() (*CheckInfo, *http.Response, error) {
	return r.ApiService.PostChangesChangeIdRevisionsRevisionIdChecksCheckIdExecute(r)
}

/*
PostChangesChangeIdRevisionsRevisionIdChecksCheckId Update Check

Updates a check. The semantics are the same as for CreateCheck.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param changeId
 @param revisionId
 @param checkId
 @return ApiPostChangesChangeIdRevisionsRevisionIdChecksCheckIdRequest
*/
func (a *ChangesAPIService) PostChangesChangeIdRevisionsRevisionIdChecksCheckId(ctx context.Context, changeId string, revisionId string, checkId string) ApiPostChangesChangeIdRevisionsRevisionIdChecksCheckIdRequest {
	return ApiPostChangesChangeIdRevisionsRevisionIdChecksCheckIdRequest{
		ApiService: a,
		ctx: ctx,
		changeId: changeId,
		revisionId: revisionId,
		checkId: checkId,
	}
}

// Execute executes the request
//  @return CheckInfo
func (a *ChangesAPIService) PostChangesChangeIdRevisionsRevisionIdChecksCheckIdExecute(r ApiPostChangesChangeIdRevisionsRevisionIdChecksCheckIdRequest) (*CheckInfo, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CheckInfo
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ChangesAPIService.PostChangesChangeIdRevisionsRevisionIdChecksCheckId")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/changes/{change-id}/revisions/{revision-id}/checks/{check-id}"
	localVarPath = strings.Replace(localVarPath, "{"+"change-id"+"}", url.PathEscape(parameterValueToString(r.changeId, "changeId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"revision-id"+"}", url.PathEscape(parameterValueToString(r.revisionId, "revisionId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"check-id"+"}", url.PathEscape(parameterValueToString(r.checkId, "checkId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "application/x-www-form-urlencoded"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.checkInput
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v CheckInfo
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPostChangesChangeIdRevisionsRevisionIdChecksCheckIdRerunRequest struct {
	ctx context.Context
	ApiService *ChangesAPIService
	changeId string
	revisionId string
	checkId string
	rerunInput *RerunInput
}

func (r ApiPostChangesChangeIdRevisionsRevisionIdChecksCheckIdRerunRequest) RerunInput(rerunInput RerunInput) ApiPostChangesChangeIdRevisionsRevisionIdChecksCheckIdRerunRequest {
	r.rerunInput = &rerunInput
	return r
}

func (r ApiPostChangesChangeIdRevisionsRevisionIdChecksCheckIdRerunRequest) Execute() (*CheckInfo, *http.Response, error) {
	return r.ApiService.PostChangesChangeIdRevisionsRevisionIdChecksCheckIdRerunExecute(r)
}

/*
PostChangesChangeIdRevisionsRevisionIdChecksCheckIdRerun Rerun Check

Reruns a check. As response the CheckInfo entity is returned that describes the created check.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param changeId
 @param revisionId
 @param checkId
 @return ApiPostChangesChangeIdRevisionsRevisionIdChecksCheckIdRerunRequest
*/
func (a *ChangesAPIService) PostChangesChangeIdRevisionsRevisionIdChecksCheckIdRerun(ctx context.Context, changeId string, revisionId string, checkId string) ApiPostChangesChangeIdRevisionsRevisionIdChecksCheckIdRerunRequest {
	return ApiPostChangesChangeIdRevisionsRevisionIdChecksCheckIdRerunRequest{
		ApiService: a,
		ctx: ctx,
		changeId: changeId,
		revisionId: revisionId,
		checkId: checkId,
	}
}

// Execute executes the request
//  @return CheckInfo
func (a *ChangesAPIService) PostChangesChangeIdRevisionsRevisionIdChecksCheckIdRerunExecute(r ApiPostChangesChangeIdRevisionsRevisionIdChecksCheckIdRerunRequest) (*CheckInfo, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CheckInfo
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ChangesAPIService.PostChangesChangeIdRevisionsRevisionIdChecksCheckIdRerun")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/changes/{change-id}/revisions/{revision-id}/checks/{check-id}/rerun"
	localVarPath = strings.Replace(localVarPath, "{"+"change-id"+"}", url.PathEscape(parameterValueToString(r.changeId, "changeId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"revision-id"+"}", url.PathEscape(parameterValueToString(r.revisionId, "revisionId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"check-id"+"}", url.PathEscape(parameterValueToString(r.checkId, "checkId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "application/x-www-form-urlencoded"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.rerunInput
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
