/*
Gerrit Checks Plugin REST API

REST endpoints contributed by the checks plugin. Paths, parameters and payload schemas are generated statically from the plugin's REST bindings; human-authored summaries, descriptions and examples are mined from the plugin's rest-api*.md and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package checksclient

import (
	"encoding/json"
	"fmt"
)

// CheckerStatus the model 'CheckerStatus'
type CheckerStatus string

// List of CheckerStatus
const (
	CHECKERSTATUS_ENABLED CheckerStatus = "ENABLED"
	CHECKERSTATUS_DISABLED CheckerStatus = "DISABLED"
)

// All allowed values of CheckerStatus enum
var AllowedCheckerStatusEnumValues = []CheckerStatus{
	"ENABLED",
	"DISABLED",
}

func (v *CheckerStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CheckerStatus(value)
	for _, existing := range AllowedCheckerStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CheckerStatus", value)
}

// NewCheckerStatusFromValue returns a pointer to a valid CheckerStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCheckerStatusFromValue(v string) (*CheckerStatus, error) {
	ev := CheckerStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CheckerStatus: valid values are %v", v, AllowedCheckerStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CheckerStatus) IsValid() bool {
	for _, existing := range AllowedCheckerStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CheckerStatus value
func (v CheckerStatus) Ptr() *CheckerStatus {
	return &v
}

type NullableCheckerStatus struct {
	value *CheckerStatus
	isSet bool
}

func (v NullableCheckerStatus) Get() *CheckerStatus {
	return v.value
}

func (v *NullableCheckerStatus) Set(val *CheckerStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckerStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckerStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckerStatus(val *CheckerStatus) *NullableCheckerStatus {
	return &NullableCheckerStatus{value: val, isSet: true}
}

func (v NullableCheckerStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckerStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

