/*
Gerrit Checks Plugin REST API

REST endpoints contributed by the checks plugin. Paths, parameters and payload schemas are generated statically from the plugin's REST bindings; human-authored summaries, descriptions and examples are mined from the plugin's rest-api*.md and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package checksclient

import (
	"encoding/json"
)

// checks if the RerunInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RerunInput{}

// RerunInput struct for RerunInput
type RerunInput struct {
	// Notify handling that defines to whom email notifications should be sent when the combined check state changes due to rerunning this check. Allowed values are NONE, OWNER, OWNER_REVIEWERS and ALL. If not set, the default is OWNER.
	Notify *NotifyHandling `json:"notify,omitempty"`
	// Additional information about whom to notify when the combined check state changes due to rerunning this check as a map of recipient type to NotifyInfo entity. Regardless of this setting there are no email notifications for rerunning checks on non-current patch sets.
	NotifyDetails map[string]NotifyInfo `json:"notify_details,omitempty"`
}

// NewRerunInput instantiates a new RerunInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRerunInput() *RerunInput {
	this := RerunInput{}
	return &this
}

// NewRerunInputWithDefaults instantiates a new RerunInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRerunInputWithDefaults() *RerunInput {
	this := RerunInput{}
	return &this
}

// GetNotify returns the Notify field value if set, zero value otherwise.
func (o *RerunInput) GetNotify() NotifyHandling {
	if o == nil || IsNil(o.Notify) {
		var ret NotifyHandling
		return ret
	}
	return *o.Notify
}

// GetNotifyOk returns a tuple with the Notify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RerunInput) GetNotifyOk() (*NotifyHandling, bool) {
	if o == nil || IsNil(o.Notify) {
		return nil, false
	}
	return o.Notify, true
}

// HasNotify returns a boolean if a field has been set.
func (o *RerunInput) HasNotify() bool {
	if o != nil && !IsNil(o.Notify) {
		return true
	}

	return false
}

// SetNotify gets a reference to the given NotifyHandling and assigns it to the Notify field.
func (o *RerunInput) SetNotify(v NotifyHandling) {
	o.Notify = &v
}

// GetNotifyDetails returns the NotifyDetails field value if set, zero value otherwise.
func (o *RerunInput) GetNotifyDetails() map[string]NotifyInfo {
	if o == nil || IsNil(o.NotifyDetails) {
		var ret map[string]NotifyInfo
		return ret
	}
	return o.NotifyDetails
}

// GetNotifyDetailsOk returns a tuple with the NotifyDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RerunInput) GetNotifyDetailsOk() (map[string]NotifyInfo, bool) {
	if o == nil || IsNil(o.NotifyDetails) {
		return map[string]NotifyInfo{}, false
	}
	return o.NotifyDetails, true
}

// HasNotifyDetails returns a boolean if a field has been set.
func (o *RerunInput) HasNotifyDetails() bool {
	if o != nil && !IsNil(o.NotifyDetails) {
		return true
	}

	return false
}

// SetNotifyDetails gets a reference to the given map[string]NotifyInfo and assigns it to the NotifyDetails field.
func (o *RerunInput) SetNotifyDetails(v map[string]NotifyInfo) {
	o.NotifyDetails = v
}

func (o RerunInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RerunInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Notify) {
		toSerialize["notify"] = o.Notify
	}
	if !IsNil(o.NotifyDetails) {
		toSerialize["notify_details"] = o.NotifyDetails
	}
	return toSerialize, nil
}

type NullableRerunInput struct {
	value *RerunInput
	isSet bool
}

func (v NullableRerunInput) Get() *RerunInput {
	return v.value
}

func (v *NullableRerunInput) Set(val *RerunInput) {
	v.value = val
	v.isSet = true
}

func (v NullableRerunInput) IsSet() bool {
	return v.isSet
}

func (v *NullableRerunInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRerunInput(val *RerunInput) *NullableRerunInput {
	return &NullableRerunInput{value: val, isSet: true}
}

func (v NullableRerunInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRerunInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


