/*
Gerrit Checks Plugin REST API

REST endpoints contributed by the checks plugin. Paths, parameters and payload schemas are generated statically from the plugin's REST bindings; human-authored summaries, descriptions and examples are mined from the plugin's rest-api*.md and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package checksclient

import (
	"encoding/json"
)

// checks if the CheckerInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckerInput{}

// CheckerInput struct for CheckerInput
type CheckerInput struct {
	// The UUID of the checker.
	Uuid *string `json:"uuid,omitempty"`
	// The name of the checker.
	Name *string `json:"name,omitempty"`
	// The description of the checker.
	Description *string `json:"description,omitempty"`
	// The URL of the checker.
	Url *string `json:"url,omitempty"`
	// The (exact) name of the repository for which the checker applies.
	Repository *string `json:"repository,omitempty"`
	// The status of the checker; one of ENABLED or DISABLED.
	Status *CheckerStatus `json:"status,omitempty"`
	// A list of conditions that describe when the checker should block change submission.
	Blocking []BlockingCondition `json:"blocking,omitempty"`
	// A query that limits changes for which the checker is relevant.
	Query *string `json:"query,omitempty"`
}

// NewCheckerInput instantiates a new CheckerInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckerInput() *CheckerInput {
	this := CheckerInput{}
	return &this
}

// NewCheckerInputWithDefaults instantiates a new CheckerInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckerInputWithDefaults() *CheckerInput {
	this := CheckerInput{}
	return &this
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *CheckerInput) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckerInput) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *CheckerInput) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *CheckerInput) SetUuid(v string) {
	o.Uuid = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CheckerInput) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckerInput) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CheckerInput) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CheckerInput) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CheckerInput) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckerInput) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CheckerInput) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CheckerInput) SetDescription(v string) {
	o.Description = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *CheckerInput) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckerInput) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *CheckerInput) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *CheckerInput) SetUrl(v string) {
	o.Url = &v
}

// GetRepository returns the Repository field value if set, zero value otherwise.
func (o *CheckerInput) GetRepository() string {
	if o == nil || IsNil(o.Repository) {
		var ret string
		return ret
	}
	return *o.Repository
}

// GetRepositoryOk returns a tuple with the Repository field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckerInput) GetRepositoryOk() (*string, bool) {
	if o == nil || IsNil(o.Repository) {
		return nil, false
	}
	return o.Repository, true
}

// HasRepository returns a boolean if a field has been set.
func (o *CheckerInput) HasRepository() bool {
	if o != nil && !IsNil(o.Repository) {
		return true
	}

	return false
}

// SetRepository gets a reference to the given string and assigns it to the Repository field.
func (o *CheckerInput) SetRepository(v string) {
	o.Repository = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CheckerInput) GetStatus() CheckerStatus {
	if o == nil || IsNil(o.Status) {
		var ret CheckerStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckerInput) GetStatusOk() (*CheckerStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CheckerInput) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given CheckerStatus and assigns it to the Status field.
func (o *CheckerInput) SetStatus(v CheckerStatus) {
	o.Status = &v
}

// GetBlocking returns the Blocking field value if set, zero value otherwise.
func (o *CheckerInput) GetBlocking() []BlockingCondition {
	if o == nil || IsNil(o.Blocking) {
		var ret []BlockingCondition
		return ret
	}
	return o.Blocking
}

// GetBlockingOk returns a tuple with the Blocking field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckerInput) GetBlockingOk() ([]BlockingCondition, bool) {
	if o == nil || IsNil(o.Blocking) {
		return nil, false
	}
	return o.Blocking, true
}

// HasBlocking returns a boolean if a field has been set.
func (o *CheckerInput) HasBlocking() bool {
	if o != nil && !IsNil(o.Blocking) {
		return true
	}

	return false
}

// SetBlocking gets a reference to the given []BlockingCondition and assigns it to the Blocking field.
func (o *CheckerInput) SetBlocking(v []BlockingCondition) {
	o.Blocking = v
}

// GetQuery returns the Query field value if set, zero value otherwise.
func (o *CheckerInput) GetQuery() string {
	if o == nil || IsNil(o.Query) {
		var ret string
		return ret
	}
	return *o.Query
}

// GetQueryOk returns a tuple with the Query field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckerInput) GetQueryOk() (*string, bool) {
	if o == nil || IsNil(o.Query) {
		return nil, false
	}
	return o.Query, true
}

// HasQuery returns a boolean if a field has been set.
func (o *CheckerInput) HasQuery() bool {
	if o != nil && !IsNil(o.Query) {
		return true
	}

	return false
}

// SetQuery gets a reference to the given string and assigns it to the Query field.
func (o *CheckerInput) SetQuery(v string) {
	o.Query = &v
}

func (o CheckerInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckerInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Repository) {
		toSerialize["repository"] = o.Repository
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Blocking) {
		toSerialize["blocking"] = o.Blocking
	}
	if !IsNil(o.Query) {
		toSerialize["query"] = o.Query
	}
	return toSerialize, nil
}

type NullableCheckerInput struct {
	value *CheckerInput
	isSet bool
}

func (v NullableCheckerInput) Get() *CheckerInput {
	return v.value
}

func (v *NullableCheckerInput) Set(val *CheckerInput) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckerInput) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckerInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckerInput(val *CheckerInput) *NullableCheckerInput {
	return &NullableCheckerInput{value: val, isSet: true}
}

func (v NullableCheckerInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckerInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


