/*
Gerrit Checks Plugin REST API

REST endpoints contributed by the checks plugin. Paths, parameters and payload schemas are generated statically from the plugin's REST bindings; human-authored summaries, descriptions and examples are mined from the plugin's rest-api*.md and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package checksclient

import (
	"encoding/json"
)

// checks if the CheckSubmitImpactInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckSubmitImpactInfo{}

// CheckSubmitImpactInfo struct for CheckSubmitImpactInfo
type CheckSubmitImpactInfo struct {
	Required *bool `json:"required,omitempty"`
}

// NewCheckSubmitImpactInfo instantiates a new CheckSubmitImpactInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckSubmitImpactInfo() *CheckSubmitImpactInfo {
	this := CheckSubmitImpactInfo{}
	return &this
}

// NewCheckSubmitImpactInfoWithDefaults instantiates a new CheckSubmitImpactInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckSubmitImpactInfoWithDefaults() *CheckSubmitImpactInfo {
	this := CheckSubmitImpactInfo{}
	return &this
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *CheckSubmitImpactInfo) GetRequired() bool {
	if o == nil || IsNil(o.Required) {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckSubmitImpactInfo) GetRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *CheckSubmitImpactInfo) HasRequired() bool {
	if o != nil && !IsNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *CheckSubmitImpactInfo) SetRequired(v bool) {
	o.Required = &v
}

func (o CheckSubmitImpactInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckSubmitImpactInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	return toSerialize, nil
}

type NullableCheckSubmitImpactInfo struct {
	value *CheckSubmitImpactInfo
	isSet bool
}

func (v NullableCheckSubmitImpactInfo) Get() *CheckSubmitImpactInfo {
	return v.value
}

func (v *NullableCheckSubmitImpactInfo) Set(val *CheckSubmitImpactInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckSubmitImpactInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckSubmitImpactInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckSubmitImpactInfo(val *CheckSubmitImpactInfo) *NullableCheckSubmitImpactInfo {
	return &NullableCheckSubmitImpactInfo{value: val, isSet: true}
}

func (v NullableCheckSubmitImpactInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckSubmitImpactInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


