/*
Gerrit Checks Plugin REST API

REST endpoints contributed by the checks plugin. Paths, parameters and payload schemas are generated statically from the plugin's REST bindings; human-authored summaries, descriptions and examples are mined from the plugin's rest-api*.md and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package checksclient

import (
	"encoding/json"
)

// checks if the CheckInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckInfo{}

// CheckInfo struct for CheckInfo
type CheckInfo struct {
	Repository *string `json:"repository,omitempty"`
	ChangeNumber *int32 `json:"change_number,omitempty"`
	PatchSetId *int32 `json:"patch_set_id,omitempty"`
	CheckerUuid *string `json:"checker_uuid,omitempty"`
	State *CheckState `json:"state,omitempty"`
	Message *string `json:"message,omitempty"`
	Url *string `json:"url,omitempty"`
	Started *string `json:"started,omitempty"`
	Finished *string `json:"finished,omitempty"`
	Created *string `json:"created,omitempty"`
	Updated *string `json:"updated,omitempty"`
	CheckerName *string `json:"checker_name,omitempty"`
	CheckerStatus *CheckerStatus `json:"checker_status,omitempty"`
	Blocking []BlockingCondition `json:"blocking,omitempty"`
	SubmitImpact *CheckSubmitImpactInfo `json:"submit_impact,omitempty"`
	CheckerDescription *string `json:"checker_description,omitempty"`
}

// NewCheckInfo instantiates a new CheckInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckInfo() *CheckInfo {
	this := CheckInfo{}
	return &this
}

// NewCheckInfoWithDefaults instantiates a new CheckInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckInfoWithDefaults() *CheckInfo {
	this := CheckInfo{}
	return &this
}

// GetRepository returns the Repository field value if set, zero value otherwise.
func (o *CheckInfo) GetRepository() string {
	if o == nil || IsNil(o.Repository) {
		var ret string
		return ret
	}
	return *o.Repository
}

// GetRepositoryOk returns a tuple with the Repository field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckInfo) GetRepositoryOk() (*string, bool) {
	if o == nil || IsNil(o.Repository) {
		return nil, false
	}
	return o.Repository, true
}

// HasRepository returns a boolean if a field has been set.
func (o *CheckInfo) HasRepository() bool {
	if o != nil && !IsNil(o.Repository) {
		return true
	}

	return false
}

// SetRepository gets a reference to the given string and assigns it to the Repository field.
func (o *CheckInfo) SetRepository(v string) {
	o.Repository = &v
}

// GetChangeNumber returns the ChangeNumber field value if set, zero value otherwise.
func (o *CheckInfo) GetChangeNumber() int32 {
	if o == nil || IsNil(o.ChangeNumber) {
		var ret int32
		return ret
	}
	return *o.ChangeNumber
}

// GetChangeNumberOk returns a tuple with the ChangeNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckInfo) GetChangeNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.ChangeNumber) {
		return nil, false
	}
	return o.ChangeNumber, true
}

// HasChangeNumber returns a boolean if a field has been set.
func (o *CheckInfo) HasChangeNumber() bool {
	if o != nil && !IsNil(o.ChangeNumber) {
		return true
	}

	return false
}

// SetChangeNumber gets a reference to the given int32 and assigns it to the ChangeNumber field.
func (o *CheckInfo) SetChangeNumber(v int32) {
	o.ChangeNumber = &v
}

// GetPatchSetId returns the PatchSetId field value if set, zero value otherwise.
func (o *CheckInfo) GetPatchSetId() int32 {
	if o == nil || IsNil(o.PatchSetId) {
		var ret int32
		return ret
	}
	return *o.PatchSetId
}

// GetPatchSetIdOk returns a tuple with the PatchSetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckInfo) GetPatchSetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.PatchSetId) {
		return nil, false
	}
	return o.PatchSetId, true
}

// HasPatchSetId returns a boolean if a field has been set.
func (o *CheckInfo) HasPatchSetId() bool {
	if o != nil && !IsNil(o.PatchSetId) {
		return true
	}

	return false
}

// SetPatchSetId gets a reference to the given int32 and assigns it to the PatchSetId field.
func (o *CheckInfo) SetPatchSetId(v int32) {
	o.PatchSetId = &v
}

// GetCheckerUuid returns the CheckerUuid field value if set, zero value otherwise.
func (o *CheckInfo) GetCheckerUuid() string {
	if o == nil || IsNil(o.CheckerUuid) {
		var ret string
		return ret
	}
	return *o.CheckerUuid
}

// GetCheckerUuidOk returns a tuple with the CheckerUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckInfo) GetCheckerUuidOk() (*string, bool) {
	if o == nil || IsNil(o.CheckerUuid) {
		return nil, false
	}
	return o.CheckerUuid, true
}

// HasCheckerUuid returns a boolean if a field has been set.
func (o *CheckInfo) HasCheckerUuid() bool {
	if o != nil && !IsNil(o.CheckerUuid) {
		return true
	}

	return false
}

// SetCheckerUuid gets a reference to the given string and assigns it to the CheckerUuid field.
func (o *CheckInfo) SetCheckerUuid(v string) {
	o.CheckerUuid = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *CheckInfo) GetState() CheckState {
	if o == nil || IsNil(o.State) {
		var ret CheckState
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckInfo) GetStateOk() (*CheckState, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *CheckInfo) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given CheckState and assigns it to the State field.
func (o *CheckInfo) SetState(v CheckState) {
	o.State = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CheckInfo) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckInfo) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CheckInfo) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CheckInfo) SetMessage(v string) {
	o.Message = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *CheckInfo) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckInfo) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *CheckInfo) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *CheckInfo) SetUrl(v string) {
	o.Url = &v
}

// GetStarted returns the Started field value if set, zero value otherwise.
func (o *CheckInfo) GetStarted() string {
	if o == nil || IsNil(o.Started) {
		var ret string
		return ret
	}
	return *o.Started
}

// GetStartedOk returns a tuple with the Started field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckInfo) GetStartedOk() (*string, bool) {
	if o == nil || IsNil(o.Started) {
		return nil, false
	}
	return o.Started, true
}

// HasStarted returns a boolean if a field has been set.
func (o *CheckInfo) HasStarted() bool {
	if o != nil && !IsNil(o.Started) {
		return true
	}

	return false
}

// SetStarted gets a reference to the given string and assigns it to the Started field.
func (o *CheckInfo) SetStarted(v string) {
	o.Started = &v
}

// GetFinished returns the Finished field value if set, zero value otherwise.
func (o *CheckInfo) GetFinished() string {
	if o == nil || IsNil(o.Finished) {
		var ret string
		return ret
	}
	return *o.Finished
}

// GetFinishedOk returns a tuple with the Finished field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckInfo) GetFinishedOk() (*string, bool) {
	if o == nil || IsNil(o.Finished) {
		return nil, false
	}
	return o.Finished, true
}

// HasFinished returns a boolean if a field has been set.
func (o *CheckInfo) HasFinished() bool {
	if o != nil && !IsNil(o.Finished) {
		return true
	}

	return false
}

// SetFinished gets a reference to the given string and assigns it to the Finished field.
func (o *CheckInfo) SetFinished(v string) {
	o.Finished = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *CheckInfo) GetCreated() string {
	if o == nil || IsNil(o.Created) {
		var ret string
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckInfo) GetCreatedOk() (*string, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *CheckInfo) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given string and assigns it to the Created field.
func (o *CheckInfo) SetCreated(v string) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *CheckInfo) GetUpdated() string {
	if o == nil || IsNil(o.Updated) {
		var ret string
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckInfo) GetUpdatedOk() (*string, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *CheckInfo) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given string and assigns it to the Updated field.
func (o *CheckInfo) SetUpdated(v string) {
	o.Updated = &v
}

// GetCheckerName returns the CheckerName field value if set, zero value otherwise.
func (o *CheckInfo) GetCheckerName() string {
	if o == nil || IsNil(o.CheckerName) {
		var ret string
		return ret
	}
	return *o.CheckerName
}

// GetCheckerNameOk returns a tuple with the CheckerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckInfo) GetCheckerNameOk() (*string, bool) {
	if o == nil || IsNil(o.CheckerName) {
		return nil, false
	}
	return o.CheckerName, true
}

// HasCheckerName returns a boolean if a field has been set.
func (o *CheckInfo) HasCheckerName() bool {
	if o != nil && !IsNil(o.CheckerName) {
		return true
	}

	return false
}

// SetCheckerName gets a reference to the given string and assigns it to the CheckerName field.
func (o *CheckInfo) SetCheckerName(v string) {
	o.CheckerName = &v
}

// GetCheckerStatus returns the CheckerStatus field value if set, zero value otherwise.
func (o *CheckInfo) GetCheckerStatus() CheckerStatus {
	if o == nil || IsNil(o.CheckerStatus) {
		var ret CheckerStatus
		return ret
	}
	return *o.CheckerStatus
}

// GetCheckerStatusOk returns a tuple with the CheckerStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckInfo) GetCheckerStatusOk() (*CheckerStatus, bool) {
	if o == nil || IsNil(o.CheckerStatus) {
		return nil, false
	}
	return o.CheckerStatus, true
}

// HasCheckerStatus returns a boolean if a field has been set.
func (o *CheckInfo) HasCheckerStatus() bool {
	if o != nil && !IsNil(o.CheckerStatus) {
		return true
	}

	return false
}

// SetCheckerStatus gets a reference to the given CheckerStatus and assigns it to the CheckerStatus field.
func (o *CheckInfo) SetCheckerStatus(v CheckerStatus) {
	o.CheckerStatus = &v
}

// GetBlocking returns the Blocking field value if set, zero value otherwise.
func (o *CheckInfo) GetBlocking() []BlockingCondition {
	if o == nil || IsNil(o.Blocking) {
		var ret []BlockingCondition
		return ret
	}
	return o.Blocking
}

// GetBlockingOk returns a tuple with the Blocking field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckInfo) GetBlockingOk() ([]BlockingCondition, bool) {
	if o == nil || IsNil(o.Blocking) {
		return nil, false
	}
	return o.Blocking, true
}

// HasBlocking returns a boolean if a field has been set.
func (o *CheckInfo) HasBlocking() bool {
	if o != nil && !IsNil(o.Blocking) {
		return true
	}

	return false
}

// SetBlocking gets a reference to the given []BlockingCondition and assigns it to the Blocking field.
func (o *CheckInfo) SetBlocking(v []BlockingCondition) {
	o.Blocking = v
}

// GetSubmitImpact returns the SubmitImpact field value if set, zero value otherwise.
func (o *CheckInfo) GetSubmitImpact() CheckSubmitImpactInfo {
	if o == nil || IsNil(o.SubmitImpact) {
		var ret CheckSubmitImpactInfo
		return ret
	}
	return *o.SubmitImpact
}

// GetSubmitImpactOk returns a tuple with the SubmitImpact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckInfo) GetSubmitImpactOk() (*CheckSubmitImpactInfo, bool) {
	if o == nil || IsNil(o.SubmitImpact) {
		return nil, false
	}
	return o.SubmitImpact, true
}

// HasSubmitImpact returns a boolean if a field has been set.
func (o *CheckInfo) HasSubmitImpact() bool {
	if o != nil && !IsNil(o.SubmitImpact) {
		return true
	}

	return false
}

// SetSubmitImpact gets a reference to the given CheckSubmitImpactInfo and assigns it to the SubmitImpact field.
func (o *CheckInfo) SetSubmitImpact(v CheckSubmitImpactInfo) {
	o.SubmitImpact = &v
}

// GetCheckerDescription returns the CheckerDescription field value if set, zero value otherwise.
func (o *CheckInfo) GetCheckerDescription() string {
	if o == nil || IsNil(o.CheckerDescription) {
		var ret string
		return ret
	}
	return *o.CheckerDescription
}

// GetCheckerDescriptionOk returns a tuple with the CheckerDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckInfo) GetCheckerDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.CheckerDescription) {
		return nil, false
	}
	return o.CheckerDescription, true
}

// HasCheckerDescription returns a boolean if a field has been set.
func (o *CheckInfo) HasCheckerDescription() bool {
	if o != nil && !IsNil(o.CheckerDescription) {
		return true
	}

	return false
}

// SetCheckerDescription gets a reference to the given string and assigns it to the CheckerDescription field.
func (o *CheckInfo) SetCheckerDescription(v string) {
	o.CheckerDescription = &v
}

func (o CheckInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Repository) {
		toSerialize["repository"] = o.Repository
	}
	if !IsNil(o.ChangeNumber) {
		toSerialize["change_number"] = o.ChangeNumber
	}
	if !IsNil(o.PatchSetId) {
		toSerialize["patch_set_id"] = o.PatchSetId
	}
	if !IsNil(o.CheckerUuid) {
		toSerialize["checker_uuid"] = o.CheckerUuid
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Started) {
		toSerialize["started"] = o.Started
	}
	if !IsNil(o.Finished) {
		toSerialize["finished"] = o.Finished
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	if !IsNil(o.CheckerName) {
		toSerialize["checker_name"] = o.CheckerName
	}
	if !IsNil(o.CheckerStatus) {
		toSerialize["checker_status"] = o.CheckerStatus
	}
	if !IsNil(o.Blocking) {
		toSerialize["blocking"] = o.Blocking
	}
	if !IsNil(o.SubmitImpact) {
		toSerialize["submit_impact"] = o.SubmitImpact
	}
	if !IsNil(o.CheckerDescription) {
		toSerialize["checker_description"] = o.CheckerDescription
	}
	return toSerialize, nil
}

type NullableCheckInfo struct {
	value *CheckInfo
	isSet bool
}

func (v NullableCheckInfo) Get() *CheckInfo {
	return v.value
}

func (v *NullableCheckInfo) Set(val *CheckInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckInfo(val *CheckInfo) *NullableCheckInfo {
	return &NullableCheckInfo{value: val, isSet: true}
}

func (v NullableCheckInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


