/*
Gerrit Checks Plugin REST API

REST endpoints contributed by the checks plugin. Paths, parameters and payload schemas are generated statically from the plugin's REST bindings; human-authored summaries, descriptions and examples are mined from the plugin's rest-api*.md and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package checksclient

import (
	"encoding/json"
	"fmt"
)

// CheckState the model 'CheckState'
type CheckState string

// List of CheckState
const (
	CHECKSTATE_FAILED CheckState = "FAILED"
	CHECKSTATE_NOT_STARTED CheckState = "NOT_STARTED"
	CHECKSTATE_SCHEDULED CheckState = "SCHEDULED"
	CHECKSTATE_RUNNING CheckState = "RUNNING"
	CHECKSTATE_SUCCESSFUL CheckState = "SUCCESSFUL"
	CHECKSTATE_NOT_RELEVANT CheckState = "NOT_RELEVANT"
)

// All allowed values of CheckState enum
var AllowedCheckStateEnumValues = []CheckState{
	"FAILED",
	"NOT_STARTED",
	"SCHEDULED",
	"RUNNING",
	"SUCCESSFUL",
	"NOT_RELEVANT",
}

func (v *CheckState) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CheckState(value)
	for _, existing := range AllowedCheckStateEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CheckState", value)
}

// NewCheckStateFromValue returns a pointer to a valid CheckState
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCheckStateFromValue(v string) (*CheckState, error) {
	ev := CheckState(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CheckState: valid values are %v", v, AllowedCheckStateEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CheckState) IsValid() bool {
	for _, existing := range AllowedCheckStateEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CheckState value
func (v CheckState) Ptr() *CheckState {
	return &v
}

type NullableCheckState struct {
	value *CheckState
	isSet bool
}

func (v NullableCheckState) Get() *CheckState {
	return v.value
}

func (v *NullableCheckState) Set(val *CheckState) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckState) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckState(val *CheckState) *NullableCheckState {
	return &NullableCheckState{value: val, isSet: true}
}

func (v NullableCheckState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

