/*
Gerrit Checks Plugin REST API

REST endpoints contributed by the checks plugin. Paths, parameters and payload schemas are generated statically from the plugin's REST bindings; human-authored summaries, descriptions and examples are mined from the plugin's rest-api*.md and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package checksclient

import (
	"encoding/json"
)

// checks if the CheckInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckInput{}

// CheckInput struct for CheckInput
type CheckInput struct {
	CheckerUuid *string `json:"checker_uuid,omitempty"`
	State *CheckState `json:"state,omitempty"`
	Message *string `json:"message,omitempty"`
	Url *string `json:"url,omitempty"`
	Started *string `json:"started,omitempty"`
	Finished *string `json:"finished,omitempty"`
	Notify *NotifyHandling `json:"notify,omitempty"`
	NotifyDetails map[string]NotifyInfo `json:"notify_details,omitempty"`
}

// NewCheckInput instantiates a new CheckInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckInput() *CheckInput {
	this := CheckInput{}
	return &this
}

// NewCheckInputWithDefaults instantiates a new CheckInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckInputWithDefaults() *CheckInput {
	this := CheckInput{}
	return &this
}

// GetCheckerUuid returns the CheckerUuid field value if set, zero value otherwise.
func (o *CheckInput) GetCheckerUuid() string {
	if o == nil || IsNil(o.CheckerUuid) {
		var ret string
		return ret
	}
	return *o.CheckerUuid
}

// GetCheckerUuidOk returns a tuple with the CheckerUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckInput) GetCheckerUuidOk() (*string, bool) {
	if o == nil || IsNil(o.CheckerUuid) {
		return nil, false
	}
	return o.CheckerUuid, true
}

// HasCheckerUuid returns a boolean if a field has been set.
func (o *CheckInput) HasCheckerUuid() bool {
	if o != nil && !IsNil(o.CheckerUuid) {
		return true
	}

	return false
}

// SetCheckerUuid gets a reference to the given string and assigns it to the CheckerUuid field.
func (o *CheckInput) SetCheckerUuid(v string) {
	o.CheckerUuid = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *CheckInput) GetState() CheckState {
	if o == nil || IsNil(o.State) {
		var ret CheckState
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckInput) GetStateOk() (*CheckState, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *CheckInput) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given CheckState and assigns it to the State field.
func (o *CheckInput) SetState(v CheckState) {
	o.State = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CheckInput) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckInput) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CheckInput) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CheckInput) SetMessage(v string) {
	o.Message = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *CheckInput) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckInput) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *CheckInput) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *CheckInput) SetUrl(v string) {
	o.Url = &v
}

// GetStarted returns the Started field value if set, zero value otherwise.
func (o *CheckInput) GetStarted() string {
	if o == nil || IsNil(o.Started) {
		var ret string
		return ret
	}
	return *o.Started
}

// GetStartedOk returns a tuple with the Started field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckInput) GetStartedOk() (*string, bool) {
	if o == nil || IsNil(o.Started) {
		return nil, false
	}
	return o.Started, true
}

// HasStarted returns a boolean if a field has been set.
func (o *CheckInput) HasStarted() bool {
	if o != nil && !IsNil(o.Started) {
		return true
	}

	return false
}

// SetStarted gets a reference to the given string and assigns it to the Started field.
func (o *CheckInput) SetStarted(v string) {
	o.Started = &v
}

// GetFinished returns the Finished field value if set, zero value otherwise.
func (o *CheckInput) GetFinished() string {
	if o == nil || IsNil(o.Finished) {
		var ret string
		return ret
	}
	return *o.Finished
}

// GetFinishedOk returns a tuple with the Finished field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckInput) GetFinishedOk() (*string, bool) {
	if o == nil || IsNil(o.Finished) {
		return nil, false
	}
	return o.Finished, true
}

// HasFinished returns a boolean if a field has been set.
func (o *CheckInput) HasFinished() bool {
	if o != nil && !IsNil(o.Finished) {
		return true
	}

	return false
}

// SetFinished gets a reference to the given string and assigns it to the Finished field.
func (o *CheckInput) SetFinished(v string) {
	o.Finished = &v
}

// GetNotify returns the Notify field value if set, zero value otherwise.
func (o *CheckInput) GetNotify() NotifyHandling {
	if o == nil || IsNil(o.Notify) {
		var ret NotifyHandling
		return ret
	}
	return *o.Notify
}

// GetNotifyOk returns a tuple with the Notify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckInput) GetNotifyOk() (*NotifyHandling, bool) {
	if o == nil || IsNil(o.Notify) {
		return nil, false
	}
	return o.Notify, true
}

// HasNotify returns a boolean if a field has been set.
func (o *CheckInput) HasNotify() bool {
	if o != nil && !IsNil(o.Notify) {
		return true
	}

	return false
}

// SetNotify gets a reference to the given NotifyHandling and assigns it to the Notify field.
func (o *CheckInput) SetNotify(v NotifyHandling) {
	o.Notify = &v
}

// GetNotifyDetails returns the NotifyDetails field value if set, zero value otherwise.
func (o *CheckInput) GetNotifyDetails() map[string]NotifyInfo {
	if o == nil || IsNil(o.NotifyDetails) {
		var ret map[string]NotifyInfo
		return ret
	}
	return o.NotifyDetails
}

// GetNotifyDetailsOk returns a tuple with the NotifyDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckInput) GetNotifyDetailsOk() (map[string]NotifyInfo, bool) {
	if o == nil || IsNil(o.NotifyDetails) {
		return map[string]NotifyInfo{}, false
	}
	return o.NotifyDetails, true
}

// HasNotifyDetails returns a boolean if a field has been set.
func (o *CheckInput) HasNotifyDetails() bool {
	if o != nil && !IsNil(o.NotifyDetails) {
		return true
	}

	return false
}

// SetNotifyDetails gets a reference to the given map[string]NotifyInfo and assigns it to the NotifyDetails field.
func (o *CheckInput) SetNotifyDetails(v map[string]NotifyInfo) {
	o.NotifyDetails = v
}

func (o CheckInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CheckerUuid) {
		toSerialize["checker_uuid"] = o.CheckerUuid
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Started) {
		toSerialize["started"] = o.Started
	}
	if !IsNil(o.Finished) {
		toSerialize["finished"] = o.Finished
	}
	if !IsNil(o.Notify) {
		toSerialize["notify"] = o.Notify
	}
	if !IsNil(o.NotifyDetails) {
		toSerialize["notify_details"] = o.NotifyDetails
	}
	return toSerialize, nil
}

type NullableCheckInput struct {
	value *CheckInput
	isSet bool
}

func (v NullableCheckInput) Get() *CheckInput {
	return v.value
}

func (v *NullableCheckInput) Set(val *CheckInput) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckInput) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckInput(val *CheckInput) *NullableCheckInput {
	return &NullableCheckInput{value: val, isSet: true}
}

func (v NullableCheckInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


