/*
Gerrit Checks Plugin REST API

REST endpoints contributed by the checks plugin. Paths, parameters and payload schemas are generated statically from the plugin's REST bindings; human-authored summaries, descriptions and examples are mined from the plugin's rest-api*.md and merged in at build time.

API version: 3.15.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package checksclient

import (
	"encoding/json"
	"fmt"
)

// BlockingCondition the model 'BlockingCondition'
type BlockingCondition string

// List of BlockingCondition
const (
	BLOCKINGCONDITION_STATE_NOT_PASSING BlockingCondition = "STATE_NOT_PASSING"
)

// All allowed values of BlockingCondition enum
var AllowedBlockingConditionEnumValues = []BlockingCondition{
	"STATE_NOT_PASSING",
}

func (v *BlockingCondition) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BlockingCondition(value)
	for _, existing := range AllowedBlockingConditionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BlockingCondition", value)
}

// NewBlockingConditionFromValue returns a pointer to a valid BlockingCondition
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBlockingConditionFromValue(v string) (*BlockingCondition, error) {
	ev := BlockingCondition(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BlockingCondition: valid values are %v", v, AllowedBlockingConditionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BlockingCondition) IsValid() bool {
	for _, existing := range AllowedBlockingConditionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BlockingCondition value
func (v BlockingCondition) Ptr() *BlockingCondition {
	return &v
}

type NullableBlockingCondition struct {
	value *BlockingCondition
	isSet bool
}

func (v NullableBlockingCondition) Get() *BlockingCondition {
	return v.value
}

func (v *NullableBlockingCondition) Set(val *BlockingCondition) {
	v.value = val
	v.isSet = true
}

func (v NullableBlockingCondition) IsSet() bool {
	return v.isSet
}

func (v *NullableBlockingCondition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlockingCondition(val *BlockingCondition) *NullableBlockingCondition {
	return &NullableBlockingCondition{value: val, isSet: true}
}

func (v NullableBlockingCondition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlockingCondition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

